### ISSUE TITLE
Setting up on local development

### ISSUE THREAD

**Issue by fuggfuggfugg** [Someguy123/LiteVault#43]
Hi @Someguy123 

This would be a tough ask but I setup the environment on my local wondering if there was a way I could recover my ltc. 
I was able to build the app in my local environment but I guess I cannot login with my credentials as the db is empty. 

I'm not sure of the legalities but Is it remotely possible to recover if you are able to provide an archived db? or without db?

**Comment by fuggfuggfugg** [comment]
Nevermind, luckily I was able to recover in electrum and transfer to litewallet.

**Comment by mina-amanian** [comment]
Hi @fuggfuggfugg,

I saw your comment about successfully recovering your LiteVault wallet using Electrum and LiteWallet. I’m in a similar situation, as I had a LiteVault wallet but can no longer access the website and my Litecoin.

Could you kindly share how you were able to recover your funds? Any guidance would mean a lot to me.

Thanks in advance!

**Comment by fuggfuggfugg** [comment]
I wish I had written it down somewhere but here's the steps I remember. It was surprisingly easy. 

Download electrum in your local machine, and follow the steps (https://bitcoinelectrum.com/restoring-your-standard-wallet-from-seed). Create a new wallet in electrum and then restore from one of those options. I hope you have all the details saved. Either that or try sweeping (https://bitcoinelectrum.com/importing-your-private-keys-into-electrum/) your private keys.

LiteWallet is one of the official wallets and I wanted it on my phone. You can choose something similar. 

Hope it helps, all the best!
