### ISSUE TITLE
Potential Security Flaw

### ISSUE THREAD

**Issue by losh11** [Someguy123/LiteVault#9]
I am a bit concerned about the `/wallet/load` function. Anyone, who is tracking someones identifier can potentially upload random crap to someone else account.

@Someguy123

**Comment by Someguy123** [comment]
How? It's protected by the shared key. You can't save to someones wallet without the shared key (which is encrypted INSIDE the wallet)

**Comment by losh11** [comment]
This is how you explained to me about the wallet creation process:

```
Generally you'll send a POST request to /wallet/create - with the users
email (if provided). The server will return JSON, which inside of the data key
will contain an object with the users shared key and their identifier. Save
the shared key to the wallet data, encrypt+encode, and post it to
/wallet/update with the following post data:
```

I might have just gone blank stupid, but how do you check the value of the
the share key when it is encrypted?

This is my thinking - so here's my identifier:
```1f22eea-19cef1a7-9567612-a88e442```
and I'll keep the decryption key private. So when I GET data from the
identifier using the ```wallet/load``` link I get JSON with this:
```
{"error":false,"wallet":"U2FsdGVkX1+flOe7aEQlxZFk8D61Mi5lflH/dscy+b8m8H32JTLT/m+ePyTVgwuAA324tMCx1rxsMcFAf71UcaCInKujkZOI20tZAVQxsjQ3E0V+EuLwvmHVcuQI970lItfM83/e4t1QTpZTCWwOpo3X0ag2sdhfkV4gtM4jK9+9WFju7X3+2++E+UZbzINHukdK0XoLd0t8j6Q9zMjEEcL0FWSBDRiWBdVhAswtkDUEUjT2Q610hM50wlhJtdrnES5ZFkcgA9FXIfuVNf8JNzG2UjFRn8mUcwmtwpgSeW6t7yapOmbWFrDb6sXRlJ0FRr/aQCNORZjj7ki/ueOeYQ=="}
```

Can you explain everything after this again (phrase differently)? Sorry
about this..

**Comment by losh11** [comment]
Would you mind just doing the entire account creation process in cURL?

**Comment by Someguy123** [comment]
>but how do you check the value of the share key when it is encrypted?

The shared key is also kept unencrypted in the database on the server. It works as a "password" for saving the wallet since we don't want to store the users actual password for saving the wallet (otherwise someone could crack it much easier if LiteVault was compromised)

When you load the wallet, you take that "wallet" part, base64 decode it, then decrypt with AES using your password as I described in the other big comment.
